# Generated by Django 6.1.1 on 2026-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['user', 'admin'])), name='valid_account_type'),
        ),
    ]
