# Generated by Django 6.1.1 on 2026-10-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_qty', models.IntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_movements', to='products.product')),
            ],
            options={
                'db_table': 'inventory_movements',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_products_sku'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_products_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_products_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='idx_products_active'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['SALE', 'RESTOCK', 'REFUND', 'ADJUSTMENT'])), name='inv_mov_reason_valid'),
        ),
    ]
